### PR TITLE
Add wasd controls to desktop canvas

### PR DESCRIPTION
**Pull request by IsaacGemal**
# Add WASD Controls to MC-Bench

- Added WASD keyboard navigation and mouse look controls for desktop users
- Maintained OrbitControls for mobile users with simple device detection
- Implemented keyboard movement (WASD for directional, Space/Q for vertical)
- Added click-and-drag mouse look functionality
- Created useIsMobile hook for responsive control switching
- Added active state tracking to track which canvas is being interacted with at a time

Note - I used Q because shift was giving me some weird issues. We can always change it back later.
Also - I did black box the majority of Claude's code, testing it in chunks, so I'm certain there's room for improvement. 
As it stands, it's quite capable and resilient.
I did however test this on a macbook touchpad, so maybe actual mouse movement may need further testing.

### CODE REVIEW

**Comment by jannalulu** [comment]
very cool that it detects cursor location to 'wasd' in the right box

intentional to only make it turn with the mouse with a double-click instead of single-click?

I can't zoom with a touchpad, and it feels natural to be able to zoom in with a touchpad? 

wasd/mouse could theoretically be faster on laptop, it feels very slow

fwiw most video games preserve 'wasd' format (ie. it's mapped to the keys, not the letters) even when you type on a different keyboard layout, but this enforces pressing the actual keys that correspond to wasd in whatever keyboard layout you have

**Comment by IsaacGemal** [comment]
- space makes me go sideways if I'm looking down on the structure from the top

good catch, fixing that shortly

- intentional to only make it turn with the mouse with a double-click instead of single-click?

you should just be able to move the camera around with a single click of a touchpad, and drag the touchpad around. I wonder if there's a mac/windows discrepancy here.

As for the zooming in - I was having a lot of trouble combining the zoom/orbit with the wasd. I went with one or the other.
Considering at the end of the day it's a minecraft app and minecraft is controlled with wasd I figured it was better to settle on that for now.

the idea is people click on the canvas, maximize it and explore it

Also I didn't really have any issues with speed on my end, I felt it was decently fast - fast to get the whole picture but not too fast where you can't explore the interiors of the structures.

**Comment by jannalulu** [comment]
> you should just be able to move the camera around with a single click of a touchpad, and drag the touchpad around. I wonder if there's a mac/windows discrepancy here.

Possibly? I have to long click or double-click to move the camera around. That's kind of surprising though, because the onclick listener works for both OS

> As for the zooming in - I was having a lot of trouble combining the zoom/orbit with the wasd. I went with one or the other. Considering at the end of the day it's a minecraft app and minecraft is controlled with wasd I figured it was better to settle on that for now.
Yeah that's fair. Sometimes I also try to orbit with the mouse and it goes into the other box and moves the other image lol. But orbit probably makes more sense here since you can just wasd into the house. 

> the idea is people click on the canvas, maximize it and explore it

Would it make more sense to be wasd once they maximize the canvas?

**Comment by IsaacGemal** [comment]
Just for now we can always tweak it later

**Pull request merged**
